"""Formal document alignment workflow model contract constants.

This module is deliberately free of Flask, database sessions, environment
configuration, provider clients, and execution logic. It is the single source
for workflow root/item status and stage strings used by the model layer.
"""

WORKFLOW_NAME = "FORMAL_DOCUMENT_ALIGNMENT_ORCHESTRATION"
CANONICAL_INPUT = "GOVERNED_KNOWLEDGE_SOURCE"
EXECUTION_MODEL = "ASYNC_JOB_ORCHESTRATION"
DATA_POLICY = "NO_LEGACY_AND_FORMAL_DUAL_WRITE"
WORKFLOW_VERSION_V1 = "formal-document-alignment-v1"

ROOT_STATUS_QUEUED = "queued"
ROOT_STATUS_VALIDATING = "validating"
ROOT_STATUS_PROCESSING = "processing"
ROOT_STATUS_READY_FOR_REVIEW = "ready_for_review"
ROOT_STATUS_COMPLETED_WITH_WARNINGS = "completed_with_warnings"
ROOT_STATUS_BLOCKED = "blocked"
ROOT_STATUS_FAILED = "failed"

DOCUMENT_ALIGNMENT_WORKFLOW_STATUSES = frozenset({
    ROOT_STATUS_QUEUED,
    ROOT_STATUS_VALIDATING,
    ROOT_STATUS_PROCESSING,
    ROOT_STATUS_READY_FOR_REVIEW,
    ROOT_STATUS_COMPLETED_WITH_WARNINGS,
    ROOT_STATUS_BLOCKED,
    ROOT_STATUS_FAILED,
})

ROOT_STAGE_QUEUED = "queued"
ROOT_STAGE_SOURCE_VALIDATION = "source_validation"
ROOT_STAGE_TERM_EXTRACTION = "term_extraction"
ROOT_STAGE_EVIDENCE_RETRIEVAL = "evidence_retrieval"
ROOT_STAGE_DRAFT_CREATION = "draft_creation"
ROOT_STAGE_VERIFICATION = "verification"
ROOT_STAGE_FINALIZATION = "finalization"
ROOT_STAGE_TERMINAL = "terminal"

DOCUMENT_ALIGNMENT_WORKFLOW_STAGES = frozenset({
    ROOT_STAGE_QUEUED,
    ROOT_STAGE_SOURCE_VALIDATION,
    ROOT_STAGE_TERM_EXTRACTION,
    ROOT_STAGE_EVIDENCE_RETRIEVAL,
    ROOT_STAGE_DRAFT_CREATION,
    ROOT_STAGE_VERIFICATION,
    ROOT_STAGE_FINALIZATION,
    ROOT_STAGE_TERMINAL,
})

ITEM_STATUS_CANDIDATE = "candidate"
ITEM_STATUS_EVIDENCE_READY = "evidence_ready"
ITEM_STATUS_DRAFT_CREATED = "draft_created"
ITEM_STATUS_VERIFICATION_COMPLETED = "verification_completed"
ITEM_STATUS_NEEDS_REVIEW = "needs_review"
ITEM_STATUS_BLOCKED = "blocked"
ITEM_STATUS_FAILED = "failed"

DOCUMENT_ALIGNMENT_ITEM_STATUSES = frozenset({
    ITEM_STATUS_CANDIDATE,
    ITEM_STATUS_EVIDENCE_READY,
    ITEM_STATUS_DRAFT_CREATED,
    ITEM_STATUS_VERIFICATION_COMPLETED,
    ITEM_STATUS_NEEDS_REVIEW,
    ITEM_STATUS_BLOCKED,
    ITEM_STATUS_FAILED,
})

ITEM_STAGE_CANDIDATE = "candidate"
ITEM_STAGE_EVIDENCE_RETRIEVAL = "evidence_retrieval"
ITEM_STAGE_DRAFT_CREATION = "draft_creation"
ITEM_STAGE_VERIFICATION = "verification"
ITEM_STAGE_TERMINAL = "terminal"

DOCUMENT_ALIGNMENT_ITEM_STAGES = frozenset({
    ITEM_STAGE_CANDIDATE,
    ITEM_STAGE_EVIDENCE_RETRIEVAL,
    ITEM_STAGE_DRAFT_CREATION,
    ITEM_STAGE_VERIFICATION,
    ITEM_STAGE_TERMINAL,
})
