"""add terminology card

Revision ID: 410544eed294
Revises: c15be34e42d6
Create Date: 2026-06-22 19:56:30.632366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410544eed294'
down_revision = 'c15be34e42d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'terminology_card',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'scope_type',
            sa.String(length=32),
            server_default='course',
            nullable=False,
        ),
        sa.Column('course_id', sa.Integer(), nullable=True),
        sa.Column('owner_user_id', sa.Integer(), nullable=True),
        sa.Column('source_document_id', sa.Integer(), nullable=True),
        sa.Column('english_term', sa.String(length=255), nullable=False),
        sa.Column('normalized_english_term', sa.String(length=255), nullable=False),
        sa.Column('final_chinese_term', sa.String(length=255), nullable=True),
        sa.Column('normalized_chinese_term', sa.String(length=255), nullable=True),
        sa.Column('courseware_sentence', sa.Text(), nullable=True),
        sa.Column('english_evidence_chunk_id', sa.Integer(), nullable=True),
        sa.Column('chinese_evidence_chunk_id', sa.Integer(), nullable=True),
        sa.Column('english_evidence_snapshot', sa.Text(), nullable=True),
        sa.Column('chinese_evidence_snapshot', sa.Text(), nullable=True),
        sa.Column('english_evidence_score', sa.Float(), nullable=True),
        sa.Column('chinese_evidence_score', sa.Float(), nullable=True),
        sa.Column(
            'alignment_status',
            sa.String(length=64),
            server_default='unverified_translation',
            nullable=False,
        ),
        sa.Column(
            'confidence_score',
            sa.Float(),
            server_default='0',
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(length=64),
            server_default='pending_quality_control',
            nullable=False,
        ),
        sa.Column('ai_provider', sa.String(length=64), nullable=True),
        sa.Column('ai_model', sa.String(length=128), nullable=True),
        sa.Column('prompt_version', sa.String(length=64), nullable=True),
        sa.Column('score_breakdown_json', sa.Text(), server_default='{}', nullable=True),
        sa.Column('quality_flags_json', sa.Text(), server_default='[]', nullable=True),
        sa.Column('risk_note', sa.Text(), nullable=True),
        sa.Column(
            'feedback_count',
            sa.Integer(),
            server_default='0',
            nullable=False,
        ),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'course_id',
            'normalized_english_term',
            'scope_type',
            name='uq_terminology_card_course_term_scope',
        ),
        sa.UniqueConstraint(
            'owner_user_id',
            'normalized_english_term',
            'source_document_id',
            name='uq_terminology_card_personal_term_source',
        ),
    )
    op.create_index(
        'ix_terminology_card_alignment_status',
        'terminology_card',
        ['alignment_status'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_chinese_evidence_chunk_id',
        'terminology_card',
        ['chinese_evidence_chunk_id'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_course_id',
        'terminology_card',
        ['course_id'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_english_evidence_chunk_id',
        'terminology_card',
        ['english_evidence_chunk_id'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_feedback_count',
        'terminology_card',
        ['feedback_count'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_final_chinese_term',
        'terminology_card',
        ['final_chinese_term'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_normalized_chinese_term',
        'terminology_card',
        ['normalized_chinese_term'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_normalized_english_term',
        'terminology_card',
        ['normalized_english_term'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_owner_user_id',
        'terminology_card',
        ['owner_user_id'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_scope_type',
        'terminology_card',
        ['scope_type'],
        unique=False,
    )
    op.create_index(
        'ix_terminology_card_status',
        'terminology_card',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_terminology_card_status', table_name='terminology_card')
    op.drop_index('ix_terminology_card_scope_type', table_name='terminology_card')
    op.drop_index('ix_terminology_card_owner_user_id', table_name='terminology_card')
    op.drop_index(
        'ix_terminology_card_normalized_english_term',
        table_name='terminology_card',
    )
    op.drop_index(
        'ix_terminology_card_normalized_chinese_term',
        table_name='terminology_card',
    )
    op.drop_index('ix_terminology_card_final_chinese_term', table_name='terminology_card')
    op.drop_index('ix_terminology_card_feedback_count', table_name='terminology_card')
    op.drop_index(
        'ix_terminology_card_english_evidence_chunk_id',
        table_name='terminology_card',
    )
    op.drop_index('ix_terminology_card_course_id', table_name='terminology_card')
    op.drop_index(
        'ix_terminology_card_chinese_evidence_chunk_id',
        table_name='terminology_card',
    )
    op.drop_index('ix_terminology_card_alignment_status', table_name='terminology_card')
    op.drop_table('terminology_card')
    # ### end Alembic commands ###
