"""create initial schema

Revision ID: c15be34e42d6
Revises: 
Create Date: 2026-06-22 15:28:14.637025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15be34e42d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=True),
    sa.Column('chapter', sa.String(length=120), nullable=True),
    sa.Column('english_term', sa.String(length=200), nullable=True),
    sa.Column('chinese_term', sa.String(length=200), nullable=True),
    sa.Column('feedback_type', sa.String(length=80), nullable=True),
    sa.Column('feedback_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=80), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('layout_type', sa.String(length=64), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.Column('layout_provider', sa.String(length=80), nullable=True),
    sa.Column('layout_confidence', sa.Float(), nullable=True),
    sa.Column('quality_flags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=True),
    sa.Column('saved_filename', sa.String(length=260), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('layout_provider', sa.String(length=80), nullable=True),
    sa.Column('layout_status', sa.String(length=40), nullable=True),
    sa.Column('layout_warnings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('chapter', sa.String(length=120), nullable=False),
    sa.Column('english_term', sa.String(length=200), nullable=False),
    sa.Column('chinese_term', sa.String(length=200), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    op.drop_table('knowledge_document')
    op.drop_table('knowledge_chunk')
    op.drop_table('feedback')
    # ### end Alembic commands ###
